name: Add labels to issues and PRs

env:
  REPOSITORY_LABEL: GH-tooling

on:
  issues:
    types: [opened, unlabeled, reopened]
  pull_request:
    types: [opened, unlabeled]

jobs:
  add_label_repo:
    name: 'Add repo label to issues and PRs'
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: andymckay/labeler@master
        with:
          add-labels: ${{ REPOSITORY_LABEL }}

  add_label_new_issue:
    name: 'Add label "NEW" to new issues'
    needs: [add_label_repo]
    runs-on: ubuntu-latest
    if: github.event.issue && github.event.action == 'opened'
    steps:
      - name: Add label
        uses: andymckay/labeler@master
        with:
          add-labels: NEW
